import whisper
import os

def transcribe_audio(audio_file_path, model_size="base"):
    """
    Transcribes an audio file using a local Whisper model.
    model_size options: 'tiny', 'base', 'small', 'medium', 'large'
    """
    print(f"Loading Whisper '{model_size}' model... (This may take a moment on the first run)")
    
    # Load the model. 'base' is a good balance of speed and accuracy for testing.
    model = whisper.load_model(model_size)
    
    if not os.path.exists(audio_file_path):
        print(f"Error: Could not find audio file at {audio_file_path}")
        return None

    print(f"Starting transcription for: {audio_file_path}")
    try:
        # Perform the transcription
        result = model.transcribe(audio_file_path)
        transcript_text = result["text"]
        
        print("Transcription complete!")
        return transcript_text
        
    except Exception as e:
        print(f"An error occurred during transcription: {e}")
        return None

# --- Test the script ---
if __name__ == "__main__":
    # Point this to the exact file path generated by our Phase 1 script
    test_audio_path = r"audio_files/video.mp3" # Update 'video.mp3' to your actual file name
    
    transcript = transcribe_audio(test_audio_path)
    
    if transcript:
        print("\n--- Extracted Transcript ---")
        print(transcript[:500] + "...\n[Output Truncated]") # Print first 500 chars